export const FETCH_INTERESTS_REQUESTED = 'FETCH_INTERESTS_REQUESTED';
export const FETCH_INTERESTS_SUCCEEDED = 'FETCH_INTERESTS_SUCCEEDED';
export const FETCH_INTERESTS_FAILED = 'FETCH_INTERESTS_FAILED';

export const PUSH_INTEREST_REQUEST = 'PUSH_INTEREST_REQUEST';
export const PUSH_INTEREST_SUCCEEDED = 'PUSH_INTEREST_SUCCEEDED';
export const PUSH_INTEREST_FAILED = 'PUSH_INTEREST_FAILED';

export const ADD_INTEREST = 'ADD_INTEREST';
export const DELETE_INTEREST = 'DELETE_INTEREST';
export const INCREMENT_IMPORTANCE = 'INCREMENT_IMPORTANCE';
